Repository Learning-Is-Vital-In-Development/24-optimizing-java-1, pull requests merged in 2024-01, with the labels that each got.

#1 챕터별 폴더 생성
  README.md
  ch01/README.md
  ch02/README.md
  ch03/README.md
  ch04/README.md
  ch05/README.md
  ch06/README.md
  ch07/README.md
  ch08/README.md
  ch09/README.md
  ch10/README.md
  ch11/README.md
  ch12/README.md
  ch13/README.md
  ch14/README.md
  ch15/README.md
Labels: size/S

#2 남궁민 - Chapter 1, 2, 3 정리
  ch01/남궁민.md
  ch02/남궁민.md
  ch03/남궁민.md
Labels: size/XL

#8 ch 1,2,3 정리
  ch01/정찬미.md
  ch02/정찬미.md
  ch03/정찬미.md
Labels: size/L

#6 자바 최적화 Chapter 1,2,3 정리 - 서제민
  ch01/서제민.md
  ch02/서제민.md
  ch03/서제민.md
Labels: size/XL

#7 1,2,3장 정리
  ch01/양윤혁.md
  ch02/양윤혁.md
  ch03/양윤혁.md
Labels: size/L

#5 chapter 1-3
  ch01/김민기.md
  ch02/김민기.md
  ch03/김민기.md
  images/스크린샷 2024-01-06 오후 5.07.52.png
  images/스크린샷 2024-01-06 오후 5.14.02.png
  images/스크린샷 2024-01-06 오후 6.09.40.png
  images/스크린샷 2024-01-07 오후 1.30.00.png
  images/스크린샷 2024-01-07 오후 1.33.30.png
  images/스크린샷 2024-01-07 오후 1.36.58.png
  images/스크린샷 2024-01-07 오후 8.22.14.png
  images/스크린샷 2024-01-07 오후 9.31.13.png
  images/스크린샷 2024-01-07 오후 9.40.00.png
  images/스크린샷 2024-01-08 오후 9.14.49.png
  images/스크린샷 2024-01-08 오후 9.21.01.png
  images/스크린샷 2024-01-08 오후 9.43.59.png
Labels: size/L

#3 자바 최적화 1, 2, 3 chapter 정리
  ch01/최혁.md
  ch02/최혁/image.png
  ch02/최혁/최혁.md
  ch03/최혁/image-1.png
  ch03/최혁/image.png
  ch03/최혁/최혁.md
Labels: size/L

#13 ch 5 정리
  ch05/서제민.md
Labels: size/L

#10 JMeter로 부하/스트레스 테스트하기
  ch03/정찬미.md
  ch04/정찬미.md
  ch05/정찬미.md
Labels: size/L

#9 Chapter 5 - JMH(w. Gradle)로 피보나치 성능 벤치마크
  ch05/남궁민.md
Labels: size/L

#14 Chapter 6 - Garbage Collector의 종류들 (발전사)
  ch06/남궁민.md
Labels: size/L

#18 G1GC 분석해보기
  ch06/서제민.md
Labels: size/M

#16 챕터 6~7 내용 정리
  ch06/최혁/image.png
  ch06/최혁/최혁.md
Labels: size/L

#15 Chapter 6-7: 메인스트림급 GC 알아보기 (저번 주 자료 보강)
  ch06/남궁민.md
Labels: size/M
